### ISSUE TITLE
A line of credit or acknowledgement might be appropriate

### ISSUE THREAD

**Issue by eddelbuettel** [eliascarv/GaussFacts.jl#1]
Per the tweet in https://twitter.com/mhsatman/status/1547647871956049920 this arose out of seeing my package for R.

Yet there is not a single line of attribution or credit in this repo as far as I can see.  Now you are not _required_ to do that but as credit and citations are effectively the only "currency" we have, consider acknowledging the motivation.  

Thanks for considering.  Acknowledging the source of quotes is also highly recommended.

**Comment by eliascarv** [comment]
I add this section in README:
![image](https://user-images.githubusercontent.com/73039601/179062519-0816b84e-7d64-4184-ae76-b5d483ffb6d1.png)
What did you think?

**Comment by eddelbuettel** [comment]
Sounds good, a simple one liner with a hyperlink to the repo may be enough.  Mentioning me is polite but not required.  I.e

```
This package was inspired by the CRAN package [gaussfacts](https://github.com/eddelbuettel/gaussfacts) 
by [Dirk Eddelbuettel](https://dirk.eddelbuettel.com).  It uses quotes assmbled by Mike Cavers via his now 
defunct site [gaussfacts.com](https://web.archive.org/web/*/gaussfacts.com).
```

I think the gaussfacts site may be down or gone but you could try via the internet archive to see if there is a cached link. (Check. Oh, looks like I already did that.  Feel free to copy that from my README).  (Done above).

**Comment by eliascarv** [comment]
It's done!

**Comment by eddelbuettel** [comment]
Thank you!

(Two 'll' in Installation though, and I usually put 'Credits' near the end.  You may want to add 'Author' for yourself too.)

**Comment by eddelbuettel** [comment]
And I'll link back to yours too by the way, which is also the right thing to do.

**Comment by eliascarv** [comment]
Thanks!

**Comment by eddelbuettel** [comment]
Already done :)  (at github that is, the CRAN package hasn't needed an update in six years....)
